
GET http://localhost:5555


###
GET http://localhost:5555/admin

//pegando todos os estados
###
GET http://localhost:5555/estados


//procurando por estados com id = 1
###
GET http://localhost:5555/estados/1


// POST = postar
//da espaço 
//so aceita tipo json
###
POST http://localhost:5555/estados
Content-Type: application/json

{
    "nome": "Cruzeiro",
    "sigla": "CRU"
}

//PUT = alterar 
//pegando em json
###
PUT  http://localhost:5555/estados
Content-Type: application/json
{
    "id": 1,
    "nome": "Sao Paulos",
    "sigla": "PS"
}


//Delete = deletar
###
DELETE  http://localhost:5555/estados
Content-Type: application/json

{
    "id": 1
}


//////////////////////////METODOS PARA MECHER COM jogador/////////////////////


//pegando todas jogador
###
GET http://localhost:5555/jogadores


//adicionando jogador de acorgo com os estados, tipo sao paulo add santos
###
POST http://localhost:5555/jogadores
Content-Type: application/json

{
    "nome": "Teste",
    "altura": "1,75",
    "idade": "31",
    "posicao": "ATA",
    "estado_id": 2
}
